# Generated by Django 4.2.5 on 2023-10-28 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('food_stock', models.CharField(max_length=100)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_disc', models.CharField(max_length=100)),
                ('food_image', models.ImageField(upload_to='media/')),
                ('food_desc', models.TextField(max_length=200)),
                ('food_reviews', models.CharField(max_length=100)),
                ('name_chef', models.CharField(max_length=200)),
                ('role_chef', models.CharField(max_length=200)),
                ('image_chef', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_sku', models.CharField(max_length=100)),
                ('food_category', models.CharField(max_length=100)),
                ('food_tag', models.CharField(max_length=200)),
                ('product_desc', models.TextField(max_length=200)),
                ('rev_name', models.CharField(max_length=200)),
                ('rev_date', models.DateField()),
                ('rev_desc', models.TextField(max_length=200)),
                ('rev_image', models.ImageField(upload_to='media/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizzan.home')),
            ],
        ),
    ]
