# Generated by Django 4.2.5 on 2023-10-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image_chef',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='name_chef',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='role_chef',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
